# Generated by Django 5.0.6 on 2024-06-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
