# Generated by Django 5.0.6 on 2024-06-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryApp', '0006_remove_profile_profile_picture_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
